files = [ "fec_pkg.vhd",
          "fec_encoder.vhd",
          "wb_slave_fec.vhd",
          "xwb_slave_fec.vhd",
          "wb_fec_decoder.vhd",
          "fec_len_rx_pad.vhd",
          "wb_fec_mux.vhd",
          "fec_len_tx_pad.vhd",
          "fec_decoder.vhd",
          "xwb_fec.vhd",
          "xwb_fec_mux.vhd",
          "fec_hdr_gen.vhd",
          "wb_fec_encoder.vhd",
          "wb_fec.vhd"];
