`define FEC_ENC_EN                   1'h0
`define DROPP                        1'h0
`define X01                          4'h0
`define X02                          4'h2
`define X03                          4'h6
`define X12                          4'h1
`define X13                          4'h5
`define X23                          4'h3

//`define LBK_MCR_ENA_OFFSET 0
//`define LBK_MCR_ENA 32'h00000001
//`define LBK_MCR_CLR_OFFSET 1
//`define LBK_MCR_CLR 32'h00000002
//`define LBK_MCR_FDMAC_OFFSET 2
//`define LBK_MCR_FDMAC 32'h00000004
//`define ADDR_LBK_DMAC_L                5'h4
//`define ADDR_LBK_DMAC_H                5'h8
//`define ADDR_LBK_RCV_CNT               5'hc
//`define ADDR_LBK_DRP_CNT               5'h10
//`define ADDR_LBK_FWD_CNT               5'h14
